module.exports = {
  'gnf protein box': true,
  'automatic taxobox': true,
  'chembox ': true,
  editnotice: true,
  geobox: true,
  hybridbox: true,
  ichnobox: true,
  infraspeciesbox: true,
  mycomorphbox: true,
  oobox: true,
  'paraphyletic group': true,
  speciesbox: true,
  subspeciesbox: true,
  'starbox short': true,
  taxobox: true,
  nhlteamseason: true,
  'asian games bid': true,
  'canadian federal election results': true,
  'dc thomson comic strip': true,
  'daytona 24 races': true,
  edencharacter: true,
  'moldova national football team results': true,
  samurai: true,
  protein: true,
  'sheet authority': true,
  'order-of-approx': true,
  'bacterial labs': true,
  'medical resources': true,
  ordination: true,
  'hockey team coach': true,
  'hockey team gm': true,
  'pro hockey team': true,
  'hockey team player': true,
  'hockey team start': true,
  mlbbioret: true,

  book: true,
  'comic book': true,
  'comic story': true,
  'comic story arc': true,
  'comic series': true,
  'comic strip': true,
  'comic collection': true,
  'graphic novel': true,
  'trade paperback': true,
  webstrip: true,
  'short story': true,
  'reference book': true,
  media: true,
  'video game': true,
  movie: true,
  'television series': true,
  'television season': true,
  'television episode': true,
  audiobook: true,
  'book series': true,
  magazine: true,
}
